version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/hubla
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "postgres", "-p", "5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: npm run start:dev
    stdin_open: true
    tty: true

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hubla
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
